### ISSUE TITLE
GIVfarm extension August 2022

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1353]
The GIVfarm current allocation is set to end on August 19th, pending the results of [this snapshot](https://snapshot.org/#/giv.eth/proposal/0x6261172ced3883df8339db78c8495d74b74527256f320071e44d059b9c4f9612) we should extend some farms, and end others.

The extensions will include: 

| Farm |	GIV per Week	| Weeks to Run	| Total in GIV|
|---|---|---|---|
|80GIV/ETH Balancer on Mainnet	| 75,000	| 12 |	900,000 |
|100% GIV Staking on Gnosis Chain |	100,000	| < 8	 | *400,000 to 800,000 |
|Total		|	| | *1,120,000 to 1,520,000 |

*GIV staking on Gnosis Chain will run only until GIVpower launches, likely taking as little as 400,000 GIV if we hope to launch by mid September.

The farms we will end include:
- 100% GIV staking on mainnet
- GIV / DAI uniswap on mainnet
- GIV/ETH sushiswap on gnosis chain
- GIV / xDAI honeyswap on gnosis chain

We will leave the angel vault program as-is with no changes. 

The snapshot will end on August 18, and is very likely to pass, so we should have everything ready before then. This is an epic of issues required to make that happen :)

**Comment by mohammadranjbarz** [comment]
* [ ] Create a distributor file for GIV stake rewards ( startTime would be after current end time of farming)
* [ ] Create a distributor file for ETH/GIV rewards
* [ ] Setup cronjob for running new scripts
* [ ] Assign 900,000 to GIV/ETH farm on token distro (multi-sig)
* [ ] Assign 800,000 to GIV stake farm on token distro (multi-sig)
* [ ] Transfer 1,700,000 GIV to token distro @divine-comedian

**Comment by divine-comedian** [comment]
@mohammadranjbarz @mateodaza @aminlatifi Any coordination questions I will be your point person! Let's try to have this ready to go by wednesday if possible! We can chat more in the dev call tomorrow

**Comment by laurenluz** [comment]
@maryjaf - why did you reopen this issue? the extension has already been completed

**Comment by maryjaf** [comment]
> @maryjaf - why did you reopen this issue? the extension has already been completed

It was a mistake.
