### ISSUE TITLE
Gnosis Safe signature and authentication compatibility

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#2133]
Right now if you try to sign with your account on the Safe environment, you won't be able because the authentication mechanism on a safe works differently than a regular wallet 

More info [here](https://gallery.mirror.xyz/GzHNX1UvpNmBDQjQ0pQnE_wsdxoS0_yWocRGOssH4Xw)

Currently this won't allow project creation as a multisig user

**Comment by divine-comedian** [comment]
Adding to this here - comments from project survey rewards process:

----

Hey team! I am currently using our Gnosis Safe App to try to allocate GIVpower from our multisig - right now it seems nearly impossible because I need to sign a message to connect my account. 

This message signature generates a multisig tx - If I leave the app while waiting for the tx to be signed the process resets - meaning if the tx is approved and it signs the message, the next time I connect to the app I need to sign the message all over again, generating another multisig tx. 


This flow seems very impractical for multisigs - is there any way around it?

----

Currently it is impossible for a multisig to do anything on the app effectively - making the native gnosis app sort of useless :/ 

I cannot access my account, nor donate, nor boost with GIVpower without signing a message on the dapp.

**Comment by laurenluz** [comment]
@aminlatifi - can you look into this? it would be nice if multisigs could effectively use GIVpower

**Comment by laurenluz** [comment]
Actually, @aminlatifi - I just made a separate issue because this one says it needs design etc. and the scope is more broad. please have a look at #2479

**Comment by MoeNick** [comment]
@mateodaza can you please provide a task list.

**Comment by divine-comedian** [comment]
## Tasks so far
### Front-end
- [ ] Adapt wallet connection to use gnosis safe from the safe app and from wallet connect
- [ ] Handle signatures event with a timer that listens when the tx is approved by the multisig
- [ ] Send signature to backend

### Back-end:
- [ ] Manage signature using safe sdk securely
- [ ] Extend token expiration for multisg signatures

## Notes 

@mateodaza and I are discussing the timer we should set for listening when the tx is approved by the multisig - this is the maximum time a multisig can take to sign the off-chain message to sign into the dapp. I suggested 36 hours but mateo needs to check the security issues, realistically I don't think it can be done in less than 4 hours from a multisig.

**Comment by mateodaza** [comment]
> ## Tasks so far
> ### Front-end
> * [x]  Adapt wallet connection to use gnosis safe from the safe app and from wallet connect
> * [ ]  Handle signatures event with a timer that listens when the tx is approved by the multisig
> * [ ]  Send signature to backend
> 
> ### Back-end:
> * [ ]  Manage signature using safe sdk securely
> * [ ]  Extend token expiration for multisg signatures
To expand on this we need to make a session handler on the backend, we're thinking on using redis to cache these values, essentially we also have to

Frontend 
- [ ] Listen always gnosis safe event when there's a session, when a signature has been initiated 
- [ ] Request token when SignMsg event is fulfilled

Backend 
- [ ] For every multisig session initiated, we need to save the message hash generated, this is to not depend on the frontend to listen to gnosis safe event
- [ ] Handle only one session at a time per multisig
- [ ] Return the token for every request if the time expiration allows

**Comment by MoeNick** [comment]
@divine-comedian CAnsplit it up!

**Comment by CarlosQ96** [comment]
Working on the endpoint for this, started on friday. Had meeting with mateo for implementation.

**Comment by divine-comedian** [comment]
> Working on the endpoint for this, started on friday. Had meeting with mateo for implementation.

Great! Can you check out this smaller issues I made for this? I took all the sub tasks and made them into individual issues for better sprint planning 

You can see all the issues here:
https://github.com/Giveth/giveth-dapps-v2/issues/2133#workspaces/all-devs-61644589b92edf0016f6999c/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA2MzYxOA&repos=325557482,411177927,448919340,483562652,524624007,513385022,586880477,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI4MjEy

**Comment by maryjaf** [comment]
After singing in with Safe, my safe wallet address is shown correctly on header but when I Tap on my profile and the my account, in Metmask modal I select reject but the profile related to account 2 is shown although I rejected 
plz check this screen record
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a1b62f42-ce5f-4657-80e4-e73c03f5d859

Also finally I couldn't complete a happy scenario and I couldn't what problem is

**Comment by mateodaza** [comment]
> After singing in with Safe, my safe wallet address is shown correctly on header but when I Tap on my profile and the my account, in Metmask modal I select reject but the profile related to account 2 is shown although I rejected 
> 
> plz check this screen record @CarlosQ96 @mateodaza 
> 
> https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a1b62f42-ce5f-4657-80e4-e73c03f5d859
> 
> 
> 
> Also finally I couldn't complete a happy scenario and I couldn't what my problem is 
> 
> 
> 
> 

This was not ready for testing - I'll let you know when it is
