### ISSUE TITLE
GIV/xDAI farm on honeyswap-xdai ( gnosis chain)

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#776]

**Comment by aminlatifi** [comment]
- [ ] Deploy new unipool
- [ ] prepare the backend
- [ ] prepare the frontend
